### ISSUE TITLE
Issue Explorer never connects to github

### ISSUE THREAD

**Issue by mikejk8s** [stateful/vscode-issue-explorer#16]
Hi, 

I just installed this along with a coworker and we're both having the same issue - when we go through the Issue Explorer walkthrough nothing happens other than it sending us to the vscode welcome page. But it never auths to github or anything and it doesn't let me view or create issues. It just loops me back to the walk through again. 

This seems like a really awesome extension so I'd love to get to use it!

Thanks!

<img width="332" alt="CleanShot 2023-04-28 at 09 48 19@2x" src="https://user-images.githubusercontent.com/22237040/235194283-90bfbf83-9646-4f32-b383-da080fbd622c.png">

**Comment by christian-bromann** [comment]
Thanks for reporting, I will take a look!

**Comment by maddes8cht** [comment]
Which seems to be exactly the same problem as described by me in #15 .
Just another focus on the same issue that makes this extension 100 % unusable.

**Comment by maddes8cht** [comment]
This also seems to be the same as #8 
This extension is non-functional since months at least

**Comment by christian-bromann** [comment]
@mikejk8s I have a fix in place and work on releasing it.

**Comment by maddes8cht** [comment]
Thanks - this is great news to hear.

**Comment by christian-bromann** [comment]
Ok, got `v1.0.6` release which fixed the bug. I was able to create this issue. Let me know if you see any other bugs or have any feedback or ideas on the extensions. Thanks for using!
